---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: '1.24.1'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  releaseName: istio-base
  targetNamespace: istio-system
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  values: