---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: velero
spec:
  chart:
    spec:
      chart: vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: velero
      version: '0.29.1'
  interval: 1h0m0s
  releaseName: vault
  targetNamespace: velero

  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    ui:
      enabled: true