apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-storage
resources:
  - minio-credentials-sealed.yaml
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - minio-certificate.yaml
