apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio
spec:
  secretName: minio-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "minio-api.minio.svc.k8s-prod.lab"
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - minio
    - minio.minio
    - minio-api.minio.svc.k8s-prod.lab
    - minio.minio.svc.k8s-prod.lab
  issuerRef:
    name: cluster-production-ca-issuer
    kind: ClusterIssuer