apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:



    prometheus:
      enabled: true

    envoy:
      enabled: true

    hubble:
      enabled: true
      relay:
        enabled: true

      ui:
        enabled: true
      peerService:
        clusterDomain: 10.128.1.60
    etcd:
      clusterDomain: 10.128.1.60
    k8sServiceHost: 10.128.1.60
    k8sServicePort: "6443"

    operator:
      enabled: true
      tolerations: []

      peerService:
        clusterDomain: 10.128.1.60
      serviceMonitor:
        enabled: true
        interval: 30s


    kubeProxyReplacement: true
    ipam:
      mode: kubernetes

    cgroup:
      automount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
