apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:



    prometheus:
      enabled: true

    envoy:
      enabled: true

    hubble:
      enabled: true
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
      peerService:
        clusterDomain: k8s-prod.lab

      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true

    etcd:
      clusterDomain: k8s-prod.lab
    k8sServiceHost: k8s-prod.lab
    k8sServicePort: "6443"

    operator:
      enabled: true
      tolerations: []

      peerService:
        clusterDomain: k8s-prod.lab
      serviceMonitor:
        enabled: true
        interval: 30s


    kubeProxyReplacement: true
    ipam:
      mode: kubernetes

    cgroup:
      automount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
