apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:

    prometheus:
      enabled: true

    envoy:
      enabled: true

    hubble:
      enabled: true
      relay:
        enabled: true

      ui:
        enabled: true
      peerService:
        clusterDomain: k8s-prod.lab

    k8sServiceHost: 10.128.1.60
    k8sServicePort: "6443"
    l2announcements:
      enabled: true
      leaseDuration: "300s"
      leaseRenewDeadline: "30s"
      leaseRetryPeriod: "10s"

    ingressController:
      enabled: true
      loadbalancerMode: shared

    nodePort:
      enabled: true

    l7Proxy: true

    loadBalancer:
      l7:
        backend: envoy

    operator:
      enabled: true
      tolerations: []

      peerService:
        clusterDomain: k8s-prod.lab
      serviceMonitor:
        enabled: true
        interval: 30s


    kubeProxyReplacement: true
    ipam:
      mode: kubernetes

    cgroup:
      automount:
        enabled: true
      hostRoot: /sys/fs/cgroup

    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
