apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    #kubeProxyReplacement: true

    prometheus:
      enabled: true

    envoy:
      enabled: true

    hubble:
      enabled: true
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
        rollOutPods: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
    operator:
      enabled: true
      tolerations: []

      peerService:
        clusterDomain: k8s-prod.lab
      serviceMonitor:
        enabled: true
        interval: 30s


    serviceAccounts:
      operator:
        create: true
        name: cilium-operator
        automount: true
        annotations: {}
