apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:

    autoDirectNodeRoutes: true
    bgpControlPlane:
      enabled: true
      secretsNamespace:
        create: true
        name: cilium-bgp
    bpfClockProbe: false
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    ipam:
      mode: kubernetes

    l2announcements:
      enabled: true
    loadBalancer:
      algorithm: maglev
      mode: hybrid
      serviceTopology: true

    nodePort:
      enabled: true

    localRedirectPolicy: true

    hubble:
      enabled: true
      metrics:
        enableOpenMetrics: true
        enabled:
        - dns
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
        serviceMonitor:
          enabled: true
          interval: 30s
          labels:
            release: "prom-operator"
      ui:
        enabled: true



    operator:
      dashboards:
        enabled: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
          interval: "30s"
          labels:
            release: "prom-operator"

