apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    #kubeProxyReplacement: true

    prometheus:
      enabled: true

    envoy:
      enabled: true

    hubble:
      enabled: true
      peerService:
        clusterDomain: k8s-prod.lab
      serviceMonitor:
        enabled: true
        interval: 30s


    serviceAccounts:
      operator:
        create: true
        name: cilium-operator
        automount: true
        annotations: {}