apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    #kubeProxyReplacement: true

    prometheus:
      enabled: true

    envoy:
      enabled: true

    hubble:
      enabled: true
      peerService:
        clusterDomain: k8s-prod.lab
