---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC3upp6SjYXkzjPZ/kTvE4DEOxaNcJiy8UpbGZ+mTW7QehZb6usMhFAw3Ese7mt18qWdNTRBmaupO8jneWERZpd5HI6SOmSAE+XeLRoEfpIw2K0yY9UAyfNUtRaung6tDljThzC/fV1PTTxpOTDrljFwY09OOyLiYZSOTK5F0KPIgKl9mIAnf8P/jUs9hqyFMoBoq6T6/FFlTF/kRgMmWAUwltuo5gGjpk8y0Ub8xv8SilzblztJYM0KgD4tcQ8JNjSyPWXVPjGAnwj23rJMp0qxEo/USlmi62eYc46IlvAnMTGUl3aI6lsDj5JWlYc7BgcPw01TBMvfg5tc5YXn5gFRHCAXKQ7pRXYu2Wpgk9FUTPpszG+7EdMnjaeBc1gYGNtGVSGkU4kK+dpW/usS2QOFqXB2Gzl3IYMwPXBlnXRSUiQlPB2u9gHm8pr7kb2RXFZ9CcBe/rIwq5RqJDFmMvFB7ozatSkGvmn2DNHSjZN7Bb94qhIE7u4oOqxAHFLJXDbfXLyoXoJl4ujvOz2XAC/t6XuZJ3wp4Sfr/3GX52URmKAOirmCCV9zM4t1tSLXwT/+fLvG0+UFQptharTAY3DWrvpfp6DNC9kF0V29Gfr0hTOi56aopqkUzyfFbAiD383C0KOZfJRGf/6GAqgyEchrjBqwGNdlxJnpTFHk+Li4aEGpvhdZtMiKgIiTlri9nRHI7QLOTff+pqnJCPVgcgGMcLxt39hBhELjZtGdHJhlKmqvLhGkSmx
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
