apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 1m
  chart:
    spec:
      chart: rancher-latest
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
      version: 2.10.3
  values:
    hostname: rancher.lab.ftscode.de
    bootstrapPassword: admin