apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 1m
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: cattle-system
      version: 2.11.0
  values:
    hostname: rancher.prod.ftscode.de
    bootstrapPassword: admin
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - rancher-ui.prod.ftscode.de
      tls:
        - secretName: rancher-ui.tls
          hosts:
            - rancher-ui.prod.ftscode.de