---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  suspend: false
  releaseName: portainer
  interval: 30m
  install:
    createNamespace: true
  chart:
    spec:
      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: portainer
      interval: 10h
  values:
    image:
      repository: portainer/portainer-ce
    ingress:
      enabled: false
    persistence:
      enabled: true
      storageClass: nfs-client
      size: 1Gi
    service:
      type: ClusterIP