---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tekton-cert
  namespace: tekton-pipelines
spec:
  secretName: tekton-prod-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "tekton.prod.ftscode.de"
  dnsNames:
  - "tekton.prod.ftscode.de"