---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./pvc.yaml
  - ./pvc-postgres-backup.yaml
  - ./release.yaml
  - ./repository.yaml
  - ./ingress.yaml
  - ./namespace.yaml