---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-system
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`longhorn.prod.ftscode.de`)
    services:
    - kind: Service
      name: longhorn-frontend
      port: 80