---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
  namespace: kube-system
spec:
  loadBalancerIPs: true
  interfaces: ["^eth[0-9]+"]
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: l2-pool
  namespace: kube-system
spec:
  allowFirstLastIPs: Yes
  blocks:
    - start: "10.128.1.240"  #${METALLB_IP_RANGE}
      stop: "10.128.1.249"