apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pihole
  name: pihole-etc-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pihole
  name: pihole-dnsmasq-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi