---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-registry
  namespace: harbor-registry
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: "24.5.0"
      sourceRef:
        kind: HelmRepository
        name: harbor-registry
        namespace: harbor-registry
      interval: 1m
  values:
    clusterDomain: k8s-prod.lab
    externalURL: https://habor.prod.ftscode.de
    adminPassword: changeme
    persistence:
      persistentVolumeClaim:
        registry:
          size: 200Gi
    core:
      updateStrategy:
        type: Recreate
    jobservice:
      updateStrategy:
        type: Recreate
    registry:
      updateStrategy:
        type: Recreate
    exposureType: ingress
    ingress:
      core:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hostname: habor.prod.ftscode.de
        tls: true