---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: 1.16.2
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: kube-system
      interval: 1m
  values:
    expose:
      tls:
        enabled: true
        secretName: ingress-cert-habor
      type: clusterIP
    externalURL: https://habor.prod.ftscode.de
    harborAdminPassword: admin
    persistence:
      enabled: false