apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:

  values:
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-client
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        hosts:
          - prometheus.dev.ftscode.de
        tls:
          - secretName: prometheus-cert-dev
            hosts:
              - prometheus.dev.ftscode.de


    alertmanager:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        hosts:
          - alert.dev.ftscode.de
        tls:
          - secretName: alert-cert-dev
            hosts:
              - alert.dev.ftscode.de

      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-client
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
    grafana:
      enabled: true

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        hosts:
          - grafana.dev.ftscode.de
        tls:
          - secretName: grafana-cert-dev
            hosts:
              - grafana.dev.ftscode.de


      persistence:
        enabled: true
        storageClassName: nfs-client
        type: sts
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
        finalizers:
        - kubernetes.io/pvc-protection
      env:
        GF_PANELS_DISABLE_SANITIZE_HTML: "true"