---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-homelab-ftscode-de
  namespace: cert-manager
spec:
  secretName: wildcard-homelab-ftscode-de-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.homelab.ftscode.de"
  dnsNames:
  - "homelab.ftscode.de"
  - "*.homelab.ftscode.de"