apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-external-secret
spec:
  secretStoreRef:
    name: es-secret-store
    kind: SecretStore
  target:
    name: example-password
  data:
  - secretKey: mysecret
    remoteRef:
      key: path_to_secret
      property: password