apiVersion: v1
kind: Secret
metadata:
  namespace: external-secrets
  name: external-secrets
  annotations:
    kubernetes.io/service-account.name: "external-secrets"
type: kubernetes.io/service-account-token