apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: es-secret-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.k8s-prod.lab:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-role"