---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-root-ca-issuer-selfsigned
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: cluster-root-ca
  secretName: cluster-root-ca-secret
  duration: 87600h # 10y
  renewBefore: 78840h # 9y
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: cluster-root-ca-issuer-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-dev-ca-issuer
spec:
  ca:
    secretName: cluster-root-ca-secret