---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-ingress
spec:
  interval: 30m
  chart:
    spec:
      chart: gateway
      version: 1.25.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-ingress
  releaseName: istio-gateway
  targetNamespace: istio-ingress
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: istio-gateway-helm-values
    valuesKey: base-values.yaml