---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cilium
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: cilium-chart
        namespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    ipam:
      mode: kubernetes

    l2announcements:
      enabled: true
    loadBalancer:
      algorithm: maglev
      mode: hybrid
      serviceTopology: true