apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 29.0.x # auto-update to semver bugfixes only
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  interval: 15m
  timeout: 5m
  releaseName: traefik
  dependsOn:
  - name: metallb
    namespace: metallb-system
  values:
    ingressRoute:
      dashboard:
        enabled: true

    logs:
      general:
        level: DEDUB
      access:
        enabled: true

    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-prod-ftscode-de-prod-tls