---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-prod
  namespace: metallb-system
spec:
  addresses:
  - 10.128.1.200-10.128.1.219

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert-prod
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool-prod