---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./postgresql-pvc.yaml
  - ./postgresql-expose.yaml
  - ./release.yaml
  - ./repository.yaml
  - ./ingress.yaml
  - ./namespace.yaml