---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql-backup
  namespace: database
spec:
  storageClassName:  manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.180.109
    path: "/HOMELAB-PROD/k8s-data-prod01/backup/postgresdb"
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/name: postgresql
  name: pvc-postgresql-backup
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  volumeName: pv-postgresql-backup
  storageClassName:  manual
  resources:
    requests:
      storage: 5Gi