---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql
  namespace: database
spec:
  storageClassName: "network-storage"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.180.109
    path: "/HOMELAB-PROD/k8s-data-prod01/postgresdb"
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/name: postgresql
  name: pvc-postgresql
  namespace: database
spec:
  storageClassName:  "network-storage"
  volumeName: pv-postgresql
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi