---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: 16.4.16
      sourceRef:
        kind: HelmRepository
        name: postgresql
        namespace: database
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    enabled: true

    clusterDomain: k8s-prod.lab

    architecture: standalone

    primary:
      persistence:
        enabled: true
        existingClaim: postgresql-pvc
        size: "4Gi"
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "512Mi"
          cpu: "500m"