---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: '16.5.x'
      sourceRef:
        kind: HelmRepository
        name: postgresql
  maxHistory: 3
  releaseName: postgresql
  targetNamespace: database
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
