---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgresql
  namespace: postgresql
spec:
  type: "oci"
  interval: 1h0m0s
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  #interval: 1h0m0s
  #url: https://charts.bitnami.com/bitnami
