---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 10m0s
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts

#---
#apiVersion: source.toolkit.fluxcd.io/v1
#kind: HelmRepository
#metadata:
#  name: postgresql
#  namespace: database
#spec:
#  interval: 1h0m0s
#  url: https://charts.bitnami.com/bitnami
