apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    ui:
      enabled: true

    server:
      affinity: ""

      extraEnvVars:
        - name: LOG_LEVEL
          value: trace

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"

      hosts:
        - vault.dev.ftscode.de
      tls:
        - secretName: vault-dev-tls
          hosts:
            - vault.dev.ftscode.de

      ha:
        enabled: true
        raft:
          enabled: true
          setNodeId: true
          config: |
              cluster_name = "k8s-dev.lab"
              storage "raft" {
                path    = "/vault/data/"
              }

              listener "tcp" {
                address = "[::]:8200"
                cluster_address = "[::]:8201"
                tls_disable = "true"
              }
              service_registration "kubernetes" {}