---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudnative-pg
      version: '0.23.2'
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: database
  maxHistory: 3
  releaseName: cloudnative-pg
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    crds:
      create: true
    monitoring:
      podMonitorEnabled: true