---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring

spec:
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "70.4.x"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  values:
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-client
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        hosts:
          - prometheus.prod.ftscode.de
        tls:
          - secretName: prometheus-cert-prod
            hosts:
              - prometheus.prod.ftscode.de


    alertmanager:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        hosts:
          - alert.prod.ftscode.de
        tls:
          - secretName: alert-cert-prod
            hosts:
              - alert.prod.ftscode.de

      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-client
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
    grafana:
      enabled: true

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        hosts:
          - grafana.prod.ftscode.de
        tls:
          - secretName: grafana-cert-prod
            hosts:
              - grafana.prod.ftscode.de

      persistence:
        enabled: true
        storageClassName: nfs-client
        type: sts
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
        finalizers:
        - kubernetes.io/pvc-protection
      env:
        GF_PANELS_DISABLE_SANITIZE_HTML: "true"