---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  interval: 10m
  # GitLab can take a while to start up for the first time, so give it up to 15 mins before deciding it failed.
  timeout: 15m
  chart:
    spec:
      chart: gitlab
      version: 8.11.1 # gitlab@17.11.1
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: gitlab-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: ingress-nginx
      namespace: ingress-nginx

  values:
    nodeSelector:
      kubernetes.io/arch: amd64

    global:
      common:
        labels: {}

      operator:
        enabled: false

      edition: ce

      hosts:
        domain: ftscode.de
        https: true
        gitlab:
          name: gitlab.prod.ftscode.de
        smartcard:
          enabled: false
        ssh: ssh.gitlab.prod.ftscode.de

      ingress:
        apiVersion: networking.k8s.io/v1
        configureCertmanager: false
        class: nginx
        tls:
          external: true

      gitlab:
        license: {}

      initialRootPassword: {}


      minio:
        enabled: false

      grafana:
        enabled: false

      kas:
        enabled: false

      registry:
        enabled: false

      appConfig:
        smartcard:
          enabled: false
        lfs:
          enabled: false
        packages:
          enabled: false
        # The graphQL API can be slow to respond when querying for
        # pipelines with many jobs, so we increase the timeout
        # to 90 from its default of 30.
        graphQlTimeout: 90

      antiAffinity: hard
    ### END OF GLOBAL SECTION

    certmanager:
      install: false

    prometheus:
      install: false

    nginx-ingress:
      enabled: false

    registry:
      enabled: false

    gitlab-runner:
      install: false

    gitlab:
      ingress:
        tls:
          enabled: true
      webservice:
        ingress:
          enabled: true
          tls:
            enabled: true
            secretName: tls-gitlab-webservice
        minReplicas: 4
        maxReplicas: 16
        resources:
          # Requested values are based on the following Prometheus queries:
          # cpu:
          #   sum(rate(container_cpu_usage_seconds_total{namespace="gitlab", pod=~"gitlab-webservice-.*"}[5m])) by (pod)
          # memory:
          #   sum by (pod) (container_memory_max_usage_bytes{namespace="gitlab", pod=~"gitlab-webservice-.*"})
          limits:
            cpu: 12
            memory: 20G
          requests:
            cpu: 1250m
            memory: 10G
        nodeSelector:
          spack.io/node-pool: gitlab
