---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ../../base/postgresql
  #- ./ingress.yaml
  - ./postgresql-expose.yaml

patches:
  - path: postgresql-values.yaml
    target:
      kind: HelmRelease