---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC7LKfQpEcaEpX66uzP6kjn5Ql0uqv+oTi6NwdoHDhYvGClQXH966LMXE1rHXGl/sHsFoRvab28l5XESnGgeBYTUBAj7v9Isz2BcGk+Y+n2Bcoa26fKM/dICLbTm7KJIVyiSLazjWIEXotK+XkrY+zLde4RirlsggTeqcZjVtBAXvevwNPyKLwbrX6O5R9g3f5RPuWKtZUC8wV0L3cWXIf+UybEPN2r0OBuL5UGJWbd6gYgeoWM6B0SEnV4Pj5oHUs5Fvy00Jiv8QQ6LaoTxy8evnw3KAtUb3Cnzh4SWhSX42FHi2Fb0q5HlhPzOh0tpBedxYvJy9MiIenEYvn1lVZuioxsTgmsT9tjeZVZKXxjvs5dWkWAz4AubYiUZFvCXTPnPfWhMbGaYqWZMdf5KprT0cj2fsssxeu2HYD/7WaE1aXubr21aAB60vmkGg9ym7kxrgWSdxFFc0xNeUxo7FYAyZP97zVLCVSWNBSkQgrZDCYojqBQgaKrK7mhoWAvKPSEFtrwYBsi5u6qQB4NAbVkY4CSFxmOZLqPNBV40Ru5a1MMfN4ghj0h5uHXc2wHgv6bBGuqm2hJBgioRJwc/K+Ee1XdJDNicc3Rgbs3na/8Z18M/4Far9zQfDBHqA1RXwuVNTadM2LgHOSTSYDNM0wh+M+5OXt7ZyjFjtCBoYlsM9+UuWzRO/LrE36VvxL8L/Cao1XHQS7sTpSeayc1mDlqnUSQS2DFoPQFKKNATpeQ9VmD26n+lSmO
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
