---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-dev
  namespace: metallb-system
spec:
  addresses:
  - 172.18.255.200-172.18.255.225

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert-dev
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool-dev