---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgALnOnzAQuxp86Bl9r8kwEB6UW0w3z72T14T0M+I6V6eeMRSh9Uid3cpGLuTUTPSeqYfHF26v9X5vzh/54lnOXrPJ2shzguy5GK0DJBvTNvHsI4M1b9K8bIM2SABeDCdmeXbNeB2nkiu1KHngqTc/Tt2+euvsUqQ9TMQPRkh3H5IaGAw6EewfOjbRIkNHzQs1tEYDPIex/IuEfGiYbu+NbtIM5SYcC7c1p+94metQe+nH2470yN8wLesmskM0KFo5r67X/ermZdB0vdipeOCUEOtSHKY0/V1d7A9WtbNdme7JTyVfORI1hAXmKDk42hWi5Bl0JFaGUvDbgtA+dJh1urGTXuC6jq7fLOpHoSPP7TKAApuXBq+wC9Sv6EfmexaE298eeM2aUkaFOooCEXJm1mNowAxjNp3TskpgqAmY4xLy9Clq1lESL0kYnrgwremmtlgO1yg+HiPOjRvvLLaGW0piLH9qc4UbozCDoS91YjdXa8Y3TzHrSFlq1zNrxglk8+9sVrcnJ4J/fw1Z+cbgFK4AYf/3/LJOu02rj/oVqxRQ+x9zkdvFgnolBVTc2sQo4TDT8/P7RncGfjFME2I3linYavX+AhRPoaZUBnzIV4wYZiQDHsHBbtfpAdUsNAEnx8U/lU25Clx2yDUvrvPTOhr/wo+hT5JYoZ+pIsnlgI6Xn1NVx8fAJKNc0Q6BuawIxU+xHSFT0hG8c=
    MINIO_ROOT_USER: AgA+1T3ivLUcPC5lueifG6C+Vxg2aPr1jSV0JAE2fmQNAS/+W9adml6QXEsmDzmTHNS0rkop6z+8nqFZrzhfhPjQJv93OAJthZyLRyW/3E0v7HLZ4qW7k7uAwX1HPLFCuNxO3h4s75v+mlizOg+s2mjjhobFTOq2QTCcA6Y1frxM+5m8KUtDNvft4I53cklYK/izwzBa/4TRwxs1zJLZphul36oAh2ucpkRZcxi7SYsxxFuDn9ZpshvQWRS6Y/IJPCpmMywRtPfLieVnCY4hB7pGAxhabcDlVOiRb9eOL1ver8Y+fMQtJA4xOFoLX78DEajYLop5g6ZXgcupZYqaIt5EGXrMNwJGB4bbZFC9wm5KDxsroBm0U9WhiUoNc1h4fcJ5C0gWkGiE6U5r7sG89XNyAugp5cHKtfM73yLUKshqJ4t+rY1cxBRExf4Wk96SCKwMlzSbSJTQvAXhI9jkq+Mr0t0TmfETctmAwfV8VpewxgoKUdbrZ8tLzxvPFQigGQcB3O1n9z9oKyxs7jqGzqPVKXiuA4rv7DFalI+mMrJFk3osWuZR5PZBQeM6mkiXEMhCLXBMkQ9VyRGq2si5kcMVqew2EqSuA10mbStb0bmYyinSy0TUfH/qSUwJ/4yMXU5W2/851Uq1xmM4HNx+0JMA575ADSA6di6EMAMMBqtWYZMmf8ZYZHtjZJ/QE8swyl4i0bKlLw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: minio
