---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-dev
  namespace: metallb-system
spec:
  addresses:
  - 10.128.1.230-10.128.1.239

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert-dev
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool-dev