---
# yaml-language-server: $schema=https://raw.githubusercontent.com/redhat-developer/vscode-tekton/main/scheme/tekton.dev/v1beta1_Task.json
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
  #namespace: default
spec:
  params:
    - name: username
      description: "Username to greet"
      default: "World"
      type: string
  steps:
    - name: goodbye
      image: alpine:3.14
      script: |
        #!/bin/bash
        echo "Goodbye $(params.username)!"