---
# yaml-language-server: $schema=https://raw.githubusercontent.com/redhat-developer/vscode-tekton/main/scheme/tekton.dev/v1beta1_Task.json
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-task
spec:
  description: A simple example Tekton Task
  steps:
    - name: echo-step
      image: alpine:3.14
      script: |
        #!/bin/sh
        echo "Message: Hello, Tekton!"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/redhat-developer/vscode-tekton/main/scheme/tekton.dev/v1beta1_TaskRun.json
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: echo-task-run
spec:
  serviceAccountName: default
  taskRef:
    name: echo-task