apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: "2.17.1"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: sealed-secrets
      interval: 12h
  values:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
    metrics:
      serviceMonitor:
        enabled: false