---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  dependsOn:
  - name: metallb
    namespace: metallb-system
  values:
    controller:
      watchIngressWithoutClass: true
      ingressClassResource:
        default: true
      ingressClassByName: true
      config:
        client-max-body-size: 32m
        proxy-read-timeout: "300"
        proxy-send-timeout: "300"
        proxy_buffer_size: "512"
        proxy_buffers: 4 512k
        proxy_busy_buffers_size: 512k
        annotations-risk-level: Critical
      service:
        type: "LoadBalancer"
        externalTrafficPolicy: Local
        internal:
          enabled: true
          externalTrafficPolicy: "Local"
      extraArgs:
        enable-ssl-passthrough: true

      replicaCount: 1
      minAvailable: 1
      allowSnippetAnnotations: true
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4