repo:
  url: https://github.com/fkheinstein204/k8s-gitops.git
  revision: main


applications:
  - name: argocd
    app-namespace: argocd
    namespace: argocd
    path: argocd
    manifest-paths: /argocd
    sync-wave: "-5"

  - name: infrastructure
    namespace: argocd
    path: infrastructure/
    manifest-paths: /infrastructure/templates;/infrastructure/Chart.yaml;/infrastructure/values.yaml
    sync-wave: "-4"  