apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  values:
    resources:
      requests:
        cpu: 1000m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 1024Mi

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.9.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    metrics:
      enabled: true
      scrapeInterval: 30s
      scrapeTimeout: 10s
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/metrics"
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
        namespace: monitoring

    configuration:
      backupStorageLocation:
      - name: default
        provider: aws
        bucket: velero
        credential:
          name: velero-credentials
          key: cloud
        config:
          region: velero
          profile: "default"
          s3ForcePathStyle:  "true"
          s3Url: https://minio-console.prod.ftscode.de/

    credentials:
      useSecret: true
      name: velero-credentials
      existingSecret:
      secretContents:
        cloud: |
            [default]
            aws_access_key_id=tqWHvfsIcycsU6SH2iG1
            aws_secret_access_key=LUnAEotgj6XByuRBSHqhZ59TbiODBCBHe3jwtr1E

    backupsEnabled: true
    snapshotsEnabled: false
    deployNodeAgent: true