apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: gateway
      version: '1.25.2'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  releaseName: istio-gateway
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
    - name: istio-istiod
    #- name: istio-cni
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
