---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: '>=0.27.0-0'
  interval: 1h0m0s
  releaseName: vault
  targetNamespace: vault
