apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines
resources:
  - ./namespace.yaml
  - ./repository.yaml
  - ./release.yaml
  # https://github.com/tektoncd/triggers/releases
  # renovate: depName=tektoncd/triggers datasource=github-releases
  - https://github.com/tektoncd/triggers/releases/download/v0.31.0/release.yaml
  # renovate: depName=tektoncd/triggers datasource=github-releases
  - https://github.com/tektoncd/triggers/releases/download/v0.31.0/interceptors.yaml
  # https://github.com/tektoncd/dashboard/releases
  # renovate: depName=tektoncd/dashboard datasource=github-releases
  - https://github.com/tektoncd/dashboard/releases/download/v0.55.0/release.yaml