---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-pipelines
  namespace: tekton-pipelines
spec:
  interval: 30m
  releaseName: tekton-pipelines
  chart:
    spec:
      chart: cdf
      version: "v0.69.0"
      sourceRef:
        kind: HelmRepository
        name: tekton-pipelines
        namespace: tekton-pipelines
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5