---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-pipelines
  namespace: tekton-pipelines
spec:
  interval: 30m
  releaseName: tekton-pipelines
  chart:
    spec:
      chart: tekton-pipeline
      version: "1.0.5"
      sourceRef:
        kind: HelmRepository
        name: cdf
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5