---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tekton-pipelines
  namespace: tekton-pipelines
spec:
  interval: 1h
  timeout: 3m
  url: https://cdfoundation.github.io/tekton-helm-chart/