---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  interval: 5m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.36
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-charts
        namespace: flux-system