apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    server:
      affinity: ""

      extraEnvVars:
        - name: LOG_LEVEL
          value: trace

      ha:
          enabled: true
          raft:
            enabled: true
            setNodeId: true
            config: |
                cluster_name = "k8s-dev.devops.lab"
                storage "raft" {
                  path    = "/vault/data/"
                }

                listener "tcp" {
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  tls_disable = "true"
                }
                service_registration "kubernetes" {}