apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    global:
      enabled: true

    ui:
      enabled: true
      serviceType: "LoadBalancer"
      serviceNodePort: null
      externalPort: 8200

    server:
      affinity: ""

      extraEnvVars:
        - name: LOG_LEVEL
          value: trace

      ha:
          enabled: true
          replicas: 3 
          raft:
            enabled: true
            setNodeId: true
            config: |
                cluster_name = "k8s-prod.lab"
                storage "raft" {
                  path    = "/vault/data/"
                }

                listener "tcp" {
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  tls_disable = "true"
                }
                service_registration "kubernetes" {}