apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - release.yaml

configMapGenerator:
  - name: istio-base-base-values
    namespace: istio-system
    files:
      - values.yaml=istio-base-values.yaml
  - name: istio-cni-base-values
    namespace: istio-system
    files:
      - values.yaml=istio-cni-values.yaml
  - name: istio-istiod-base-values
    namespace: istio-system
    files:
      - values.yaml=istio-istiod-values.yaml
  - name: istio-ztunnel-base-values
    namespace: istio-system
    files:
      - values.yaml=istio-ztunnel-values.yaml
configurations:
  - kustomizeconfig.yaml