---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: '1.23.2'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  releaseName: istio-base
  targetNamespace: istio-system
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
  - kind: ConfigMap
    name: istio-base-base-values
  - kind: ConfigMap
    name: istio-base-overlay-values
    optional: true

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cni
      version: '1.23.2'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  releaseName: istio-cni
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
  - kind: ConfigMap
    name: istio-cni-base-values
  - kind: ConfigMap
    name: istio-cni-overlay-values
    optional: true

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: istiod
      version: '1.23.2'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  releaseName: istio-istiod
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
    - name: istio-cni
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
  - kind: ConfigMap
    name: istio-istiod-base-values
  - kind: ConfigMap
    name: istio-istiod-overlay-values
    optional: true

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ztunnel
      version: '1.23.2'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  releaseName: istio-ztunnel
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
    - name: istio-cni
    - name: istio-istiod
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
  - kind: ConfigMap
    name: istio-ztunnel-base-values
  - kind: ConfigMap
    name: istio-ztunnel-overlay-values
    optional: true