---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cni
      version: '1.23.2'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  releaseName: istio-cni
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    profile: ambient
