apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "6.x"
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      schemaConfig:
        configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: filesystem # we're storing on filesystem so there's no real persistence here.
          schema: v13
    singleBinary:
      replicas: 1
    read:
      replicas: 0
    backend:
      replicas: 0
    write:
      replicas: 0
    chunksCache:
      # -- Specifies whether memcached based chunks-cache should be enabled
      enabled: true
      # -- Amount of memory allocated to chunks-cache for object storage (in MB).
      allocatedMemory: 2048
      resources:
        limits:
          memory: 2458Mi
        requests:
          cpu: 50m
          memory: 700Mi