apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: 2.9.10
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: monitoring
      interval: 60m
  values:
    grafana:
      rbac:
        pspEnabled: false